import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:muslim_pro/features/settings/settings_provider.dart';

class AppLocalization {
  final String language;

  AppLocalization(this.language);

  static final Map<String, Map<String, String>> _localizedValues = {
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // O'ZBEK (LOTIN)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    'uz': {
      'app_name': 'Amal',
      'settings': 'Sozlamalar',
      'general': 'Umumiy',
      'language': 'Til',
      'theme': 'Ilova mavzusi',
      'dark_mode': 'Tungi rejim',
      'light_mode': 'Kunduzgi rejim',
      'font_size': 'Shrift o\'lchami',
      'notifications': 'Bildirishnomalar',
      'adhan_voice': 'Azon ovozi',
      'pre_prayer_reminder': 'Namozdan oldin eslatma (10 daq)',
      'juma_reminder': 'Juma salovoti eslatmasi',
      'test_adhan': 'Azonni sinash (3 soniyada)',
      'test_adhan_msg': 'Ilovani yoping, tez oradan Azon chalinadi',
      'about': 'Haqida',
      'version': 'Versiya',
      'team': 'Jamoamiz',
      'assalom': 'Assalomu alaykum',
      'next_prayer': 'Keyingi namoz',
      'audio_quran': 'Audio Qur\'on',
      'quran_menu': 'Qur\'oni Karim',
      'mushaf': 'Mushaf (Tajvidli)',
      'duas': 'Duolar va Salovatlar',
      'tasbeh': 'Tasbeh',
      'qibla': 'Qibla',
      'bomdod': 'Bomdod',
      'peshin': 'Peshin',
      'asr': 'Asr',
      'shom': 'Shom',
      'xufton': 'Xufton',
      'uzbek_latin': 'O\'zbek (Lotin)',
      'uzbek_cyrillic': 'Ўзбек (Кирилл)',
      'search_surah': 'Sura qidirish...',
      'quran_karim': 'Qur\'on',
      'sura': 'Sura',
      'juz': 'Juz',
      'oyat': 'OYAT',
      'copy_success': 'Oyat nusxalandi',
      'share_msg': '— Amal ilovasidan',
      'history_stats': 'Tarix va Statistika',
      'zikr_counter': 'Zikr sanagich',
      'select_language': 'Tilni tanlang',
      'hours': 'soat',
      'minutes': 'daqiqa',
      'seconds': 'soniya',
      'listen': 'Tinglash',
      'menu_subtitle_dua': 'Kirish menyusi orqali',
      'zikr_subtitle': 'Zikr sanagich',
      'qibla_subtitle': 'Yo\'nalish',
      'meccan': 'MAKKIY',
      'medinan': 'MADANIY',
      'subhanalloh': 'Subhanalloh',
      'alhamdulillah': 'Alhamdulillah',
      'allohu akbar': 'Allohu Akbar',
      'la ilaha illalloh': 'La ilaha illalloh',
      'astaghfirulloh': 'Astaghfirulloh',
      'total_count': 'Jami: ',
      'custom_zikr_hint': 'Shaxsiy zikr yozish...',
      'tonggi duolar': 'Tonggi duolar',
      'kechki duolar': 'Kechki duolar',
      'namoz duolari': 'Namoz duolari',
      'kundalik duolar': 'Kundalik duolar',
      'safar duolari': 'Safar duolari',
      'oila duolari': 'Oila duolari',
      'juma duolari': 'Juma duolari',
      'ramazon duolari': 'Ramazon duolari',
      'haj va umra': 'Haj va Umra',
      'bemorlik': 'Bemorlik',
      'qabr ziyorati': 'Qabr ziyorati',
      'salovatlar': 'Salovatlar',
      'duolar': 'Duolar',
      'error_occured': 'Xatolik yuz berdi',
      'namoz_times': 'Namoz vaqtlari',
      'current_location': 'Joriy joylashuv',
      'change': 'O\'zgartirish',
      'select_city': 'Shaharni tanlash',
      'search_city_hint': 'Shahar nomini yozing...',
      'my_location_gps': 'Mening joylashuvim (GPS)',
      'auto_detection': 'Avtomatik aniqlash',
      'calc_settings': 'Hisoblash sozlamalari',
      'calc_method': 'Hisoblash usuli',
      'madhab_title': 'Mazhab (Asr vaqti uchun)',
      'hanafi': 'Hanafiy',
      'shafi': 'Shofiiy / Boshqa',
      'gps_enabled': 'GPS orqali joylashuv yoqildi',
      'quyosh': 'Quyosh',
      'qibla_aligned': 'Qibla yo\'nalishidasiz!',
      'qibla_hint': 'Telefoningizni tekis ushlang va sekin aylantiring',
      'auto_detect_method': 'Avtomatik aniqlash',
      'auto_detect_hint': 'Mamlakatga asoslangan holda mos usulni tanlash',
      'calc_method_hint': 'Turli mintaqalar uchun turli hisoblash standartlari qo\'llaniladi. O\'zingizga mosini tanlang.',
      'location_denied': 'Joylashuvga ruxsat berilmadi',
      'location_needed': 'Joylashuvga ruxsat kerak',
      'retry': 'Qayta urinish',
      'today': 'Bugun',
      'streak': 'Davomiylik',
      'all': 'Jami',
      'last_7_days': 'Oxirgi 7 kun',
      'mon': 'Du',
      'tue': 'Se',
      'wed': 'Ch',
      'thu': 'Pa',
      'fri': 'Ju',
      'sat': 'Sh',
      'sun': 'Ya',
      'monthly_schedule': '1 Oylik jadval',
      'prayer_completed': 'namoz o\'qildi',
      'future_times': 'Kelajak vaqtlari',
      'past_day': 'O\'tgan kun',
      'full_schedule': 'To\'liq jadval',
      'completed_today': 'Bugun:',
      'of_5_prayers': '/ 5 namoz o\'qildi',
      'daily_prayers': 'Kunlik namozlar',
      'all_prayers_done': 'Barcha namozlar o\'qildi. Alloh qabul qilsin.',
      'language_sub_en': 'English',
      'language_sub_ar': 'العربية',
      'language_sub_id': 'Bahasa Indonesia',
      'language_sub_uz': 'O\'zbekcha',
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // O'ZBEK (КИРИЛЛ)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    'uz_cyr': {
      'app_name': 'Амал',
      'settings': 'Созламалар',
      'general': 'Умумий',
      'language': 'Тил',
      'theme': 'Илова мавзуси',
      'dark_mode': 'Тунги режим',
      'light_mode': 'Кундузги режим',
      'font_size': 'Шрифт ўлчами',
      'notifications': 'Билдиришномалар',
      'adhan_voice': 'Азон овози',
      'pre_prayer_reminder': 'Намоздан олдин эслатма (10 дақ)',
      'juma_reminder': 'Жума саловоти эслатмаси',
      'test_adhan': 'Азонни синаш (3 сонияда)',
      'test_adhan_msg': 'Иловани ёпинг, тез орадан Азон чалинади',
      'about': 'Ҳақида',
      'version': 'Версия',
      'team': 'Жамоамиз',
      'assalom': 'Ассалому алайкум',
      'next_prayer': 'Кейинги намоз',
      'audio_quran': 'Аудио Қуръон',
      'quran_menu': 'Қуръони Карим',
      'mushaf': 'Мусҳаф (Тажвидли)',
      'duas': 'Дуолар ва Саловатлар',
      'tasbeh': 'Тасбеҳ',
      'qibla': 'Қибла',
      'bomdod': 'Бомдод',
      'peshin': 'Пешин',
      'asr': 'Аср',
      'shom': 'Шом',
      'xufton': 'Хуфтон',
      'uzbek_latin': 'O\'zbek (Lotin)',
      'uzbek_cyrillic': 'Ўзбек (Кирилл)',
      'search_surah': 'Сура қидириш...',
      'quran_karim': 'Қуръон',
      'sura': 'Сура',
      'juz': 'Жуз',
      'oyat': 'ОЯТ',
      'copy_success': 'Оят нусхаланди',
      'share_msg': '— Амал иловасидан',
      'history_stats': 'Тарих ва Статистика',
      'zikr_counter': 'Зикр санагич',
      'select_language': 'Тилни танланг',
      'hours': 'соат',
      'minutes': 'дақиқа',
      'seconds': 'сония',
      'listen': 'Тинглаш',
      'menu_subtitle_dua': 'Кириш менюси орқали',
      'zikr_subtitle': 'Зикр санагич',
      'qibla_subtitle': 'Йўналиш',
      'meccan': 'МАККИЙ',
      'medinan': 'МАДАНИЙ',
      'subhanalloh': 'Субҳаналлоҳ',
      'alhamdulillah': 'Алҳамдулиллаҳ',
      'allohu akbar': 'Аллоҳу Акбар',
      'la ilaha illalloh': 'Ла илаҳа иллаллоҳ',
      'astaghfirulloh': 'Астағфируллоҳ',
      'total_count': 'Жами: ',
      'custom_zikr_hint': 'Шахсий зикр ёзиш...',
      'tonggi duolar': 'Тонгги дуолар',
      'kechki duolar': 'Кечки дуолар',
      'namoz duolari': 'Намоз дуолари',
      'kundalik duolar': 'Кундалик дуолар',
      'safar duolari': 'Сафар дуолари',
      'oila duolari': 'Оила дуолари',
      'juma duolari': 'Жума дуолари',
      'ramazon duolari': 'Рамазон дуолари',
      'haj va umra': 'Ҳаж ва Умра',
      'bemorlik': 'Беморлик',
      'qabr ziyorati': 'Қабр зиёрати',
      'salovatlar': 'Саловатлар',
      'duolar': 'Дуолар',
      'error_occured': 'Хатолик юз берди',
      'namoz_times': 'Намоз вақтлари',
      'current_location': 'Жорий жойлашув',
      'change': 'Ўзгартириш',
      'select_city': 'Шаҳарни танлаш',
      'search_city_hint': 'Шаҳар номини ёзинг...',
      'my_location_gps': 'Менинг жойлашувим (GPS)',
      'auto_detection': 'Автоматик аниқлаш',
      'calc_settings': 'Ҳисоблаш созламалари',
      'calc_method': 'Ҳисоблаш усули',
      'madhab_title': 'Мазҳаб (Аср вақти учун)',
      'hanafi': 'Ҳанафий',
      'shafi': 'Шофийи / Бошқа',
      'gps_enabled': 'GPS орқали жойлашув ёқилди',
      'quyosh': 'Қуёш',
      'qibla_aligned': 'Қибла йўналишидасиз!',
      'qibla_hint': 'Телефонингизни текис ушланг ва секин айлантиринг',
      'auto_detect_method': 'Автоматик аниқлаш',
      'auto_detect_hint': 'Мамлакатга асосланган ҳолда мос усулни танлаш',
      'calc_method_hint': 'Турли минтақалар учун турли ҳисоблаш стандартлари қўлланилади. Ўзингизга мосини танланг.',
      'location_denied': 'Жойлашувга рухсат берилмади',
      'location_needed': 'Жойлашувга рухсат керак',
      'retry': 'Қайта уриниш',
      'today': 'Бугун',
      'streak': 'Давомийлик',
      'all': 'Жами',
      'last_7_days': 'Охирги 7 кун',
      'mon': 'Ду',
      'tue': 'Се',
      'wed': 'Че',
      'thu': 'Па',
      'fri': 'Жу',
      'sat': 'Ша',
      'sun': 'Як',
      'monthly_schedule': '1 Ойлик жадвал',
      'prayer_completed': 'намоз ўқилди',
      'future_times': 'Келажак вақтлари',
      'past_day': 'Ўтган кун',
      'full_schedule': 'Тўлиқ жадвал',
      'completed_today': 'Бугун:',
      'of_5_prayers': '/ 5 намоз ўқилди',
      'daily_prayers': 'Кунлик намозлар',
      'all_prayers_done': 'Барча намозлар ўқилди. Аллоҳ қабул қилсин.',
      'language_sub_en': 'English',
      'language_sub_ar': 'العربية',
      'language_sub_id': 'Bahasa Indonesia',
      'language_sub_uz': 'Ўзбекча',
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // ENGLISH
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    'en': {
      'app_name': 'Amal',
      'settings': 'Settings',
      'general': 'General',
      'language': 'Language',
      'theme': 'App Theme',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'font_size': 'Font Size',
      'notifications': 'Notifications',
      'adhan_voice': 'Adhan Voice',
      'pre_prayer_reminder': 'Pre-prayer Reminder (10 min)',
      'juma_reminder': 'Jumu\'ah Salawat Reminder',
      'test_adhan': 'Test Adhan (in 3 sec)',
      'test_adhan_msg': 'Close the app, Adhan will play shortly',
      'about': 'About',
      'version': 'Version',
      'team': 'Our Team',
      'assalom': 'As-salamu alaykum',
      'next_prayer': 'Next prayer',
      'audio_quran': 'Audio Qur\'an',
      'quran_menu': 'Noble Qur\'an',
      'mushaf': 'Mushaf (Tajweed)',
      'duas': 'Duas & Salawat',
      'tasbeh': 'Tasbeeh',
      'qibla': 'Qibla',
      'bomdod': 'Fajr',
      'peshin': 'Dhuhr',
      'asr': 'Asr',
      'shom': 'Maghrib',
      'xufton': 'Isha',
      'uzbek_latin': 'Uzbek (Latin)',
      'uzbek_cyrillic': 'Uzbek (Cyrillic)',
      'search_surah': 'Search Surah...',
      'quran_karim': 'Qur\'an',
      'sura': 'Surah',
      'juz': 'Juz',
      'oyat': 'AYAH',
      'copy_success': 'Ayah copied',
      'share_msg': '— from Amal app',
      'history_stats': 'History & Stats',
      'zikr_counter': 'Dhikr Counter',
      'select_language': 'Select Language',
      'hours': 'hours',
      'minutes': 'min',
      'seconds': 'sec',
      'listen': 'Listen',
      'menu_subtitle_dua': 'via Entrance menu',
      'zikr_subtitle': 'Dhikr counter',
      'qibla_subtitle': 'Direction',
      'meccan': 'MECCAN',
      'medinan': 'MEDINAN',
      'subhanalloh': 'SubhanAllah',
      'alhamdulillah': 'Alhamdulillah',
      'allohu akbar': 'Allahu Akbar',
      'la ilaha illalloh': 'La ilaha illallah',
      'astaghfirulloh': 'Astaghfirullah',
      'total_count': 'Total: ',
      'custom_zikr_hint': 'Write custom dhikr...',
      'tonggi duolar': 'Morning Duas',
      'kechki duolar': 'Evening Duas',
      'namoz duolari': 'Prayer Duas',
      'kundalik duolar': 'Daily Duas',
      'safar duolari': 'Travel Duas',
      'oila duolari': 'Family Duas',
      'juma duolari': 'Friday Duas',
      'ramazon duolari': 'Ramadan Duas',
      'haj va umra': 'Hajj & Umrah',
      'bemorlik': 'Illness',
      'qabr ziyorati': 'Grave Visitation',
      'salovatlar': 'Salawat',
      'duolar': 'Duas',
      'error_occured': 'An error occurred',
      'namoz_times': 'Prayer Times',
      'current_location': 'Current Location',
      'change': 'Change',
      'select_city': 'Select City',
      'search_city_hint': 'Type city name...',
      'my_location_gps': 'My Location (GPS)',
      'auto_detection': 'Auto Detect',
      'calc_settings': 'Calculation Settings',
      'calc_method': 'Calculation Method',
      'madhab_title': 'Madhab (for Asr time)',
      'hanafi': 'Hanafi',
      'shafi': 'Shafi\'i / Others',
      'gps_enabled': 'GPS location enabled',
      'quyosh': 'Sunrise',
      'qibla_aligned': 'You are aligned to Qibla!',
      'qibla_hint': 'Hold your phone flat and turn slowly',
      'auto_detect_method': 'Auto Detection',
      'auto_detect_hint': 'Select method based on your country automatically',
      'calc_method_hint': 'Different regions use different calculation standards. Choose the one that suits you.',
      'location_denied': 'Location access denied',
      'location_needed': 'Location access is needed',
      'retry': 'Retry',
      'today': 'Today',
      'streak': 'Streak',
      'all': 'All',
      'last_7_days': 'Last 7 days',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'monthly_schedule': 'Monthly Schedule',
      'prayer_completed': 'prayed',
      'future_times': 'Future times',
      'past_day': 'Past day',
      'full_schedule': 'Full Schedule',
      'completed_today': 'Today:',
      'of_5_prayers': '/ 5 prayers done',
      'daily_prayers': 'Daily Prayers',
      'all_prayers_done': 'All prayers completed. May Allah accept.',
      'language_sub_en': 'English',
      'language_sub_ar': 'العربية',
      'language_sub_id': 'Bahasa Indonesia',
      'language_sub_uz': 'O\'zbekcha',
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // ARABIC (العربية)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    'ar': {
      'app_name': 'أمل',
      'settings': 'الإعدادات',
      'general': 'عام',
      'language': 'اللغة',
      'theme': 'مظهر التطبيق',
      'dark_mode': 'الوضع الداكن',
      'light_mode': 'الوضع الفاتح',
      'font_size': 'حجم الخط',
      'notifications': 'الإشعارات',
      'adhan_voice': 'صوت الأذان',
      'pre_prayer_reminder': 'تذكير قبل الصلاة (10 دقائق)',
      'juma_reminder': 'تذكير بالصلاة على النبي يوم الجمعة',
      'test_adhan': 'تجربة الأذان (خلال 3 ثوان)',
      'test_adhan_msg': 'أغلق التطبيق، سيرفع الأذان قريباً',
      'about': 'حول التطبيق',
      'version': 'الإصدار',
      'team': 'فريقنا',
      'assalom': 'السلام عليكم',
      'next_prayer': 'الصلاة القادمة',
      'audio_quran': 'القرآن الصوتي',
      'quran_menu': 'القرآن الكريم',
      'mushaf': 'المصحف (التجويد)',
      'duas': 'الأدعية والصلوات',
      'tasbeh': 'المسبحة',
      'qibla': 'القبلة',
      'bomdod': 'الفجر',
      'peshin': 'الظهر',
      'asr': 'العصر',
      'shom': 'المغرب',
      'xufton': 'العشاء',
      'uzbek_latin': 'الأوزبكية (لاتيني)',
      'uzbek_cyrillic': 'الأوزبكية (كيريلي)',
      'search_surah': 'ابحث عن سورة...',
      'quran_karim': 'القرآن',
      'sura': 'سورة',
      'juz': 'جزء',
      'oyat': 'آية',
      'copy_success': 'تم نسخ الآية',
      'share_msg': '— من تطبيق أمل',
      'history_stats': 'التاريخ والإحصائيات',
      'zikr_counter': 'عدّاد الذكر',
      'select_language': 'اختر اللغة',
      'hours': 'ساعة',
      'minutes': 'دقيقة',
      'seconds': 'ثانية',
      'listen': 'استماع',
      'menu_subtitle_dua': 'عبر قائمة الدخول',
      'zikr_subtitle': 'عدّاد الذكر',
      'qibla_subtitle': 'الاتجاه',
      'meccan': 'مكيّة',
      'medinan': 'مدنيّة',
      'subhanalloh': 'سبحان الله',
      'alhamdulillah': 'الحمد لله',
      'allohu akbar': 'الله أكبر',
      'la ilaha illalloh': 'لا إله إلا الله',
      'astaghfirulloh': 'أستغفر الله',
      'total_count': 'المجموع: ',
      'custom_zikr_hint': 'اكتب ذكرك الخاص...',
      'tonggi duolar': 'أذكار الصباح',
      'kechki duolar': 'أذكار المساء',
      'namoz duolari': 'أدعية الصلاة',
      'kundalik duolar': 'أدعية يومية',
      'safar duolari': 'أدعية السفر',
      'oila duolari': 'أدعية العائلة',
      'juma duolari': 'أدعية يوم الجمعة',
      'ramazon duolari': 'أدعية رمضان',
      'haj va umra': 'الحج والعمرة',
      'bemorlik': 'المرض',
      'qabr ziyorati': 'زيارة القبور',
      'salovatlar': 'الصلوات على النبي',
      'duolar': 'الأدعية',
      'error_occured': 'حدث خطأ ما',
      'namoz_times': 'أوقات الصلاة',
      'current_location': 'الموقع الحالي',
      'change': 'تغيير',
      'select_city': 'اختر المدينة',
      'search_city_hint': 'اكتب اسم المدينة...',
      'my_location_gps': 'موقعي (GPS)',
      'auto_detection': 'اكتشاف تلقائي',
      'calc_settings': 'إعدادات الحساب',
      'calc_method': 'طريقة الحساب',
      'madhab_title': 'المذهب (لوقت العصر)',
      'hanafi': 'الحنفي',
      'shafi': 'الشافعي / أخرى',
      'gps_enabled': 'تم تفعيل الموقع عبر GPS',
      'quyosh': 'الشروق',
      'qibla_aligned': 'أنت في اتجاه القبلة!',
      'qibla_hint': 'احمل هاتفك بشكل مسطح ودوّره ببطء',
      'auto_detect_method': 'اكتشاف تلقائي',
      'auto_detect_hint': 'تحديد طريقة الحساب الأنسب لبلدك تلقائياً',
      'calc_method_hint': 'تختلف معايير الحساب باختلاف المناطق. اختر ما يناسبك.',
      'location_denied': 'تم رفض إذن الموقع',
      'location_needed': 'الوصول إلى الموقع مطلوب',
      'retry': 'إعادة المحاولة',
      'today': 'اليوم',
      'streak': 'الاستمرارية',
      'all': 'الكل',
      'last_7_days': 'آخر 7 أيام',
      'mon': 'إثن',
      'tue': 'ثلا',
      'wed': 'أرب',
      'thu': 'خمي',
      'fri': 'جمع',
      'sat': 'سبت',
      'sun': 'أحد',
      'monthly_schedule': 'الجدول الشهري',
      'prayer_completed': 'صُلّيت',
      'future_times': 'أوقات قادمة',
      'past_day': 'يوم ماضٍ',
      'full_schedule': 'الجدول الكامل',
      'completed_today': 'اليوم:',
      'of_5_prayers': '/ 5 صلوات أُديت',
      'daily_prayers': 'الصلوات اليومية',
      'all_prayers_done': 'أُديت جميع الصلوات. تقبّل الله.',
      'language_sub_en': 'English',
      'language_sub_ar': 'العربية',
      'language_sub_id': 'Bahasa Indonesia',
      'language_sub_uz': 'O\'zbekcha',
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // INDONESIAN (Bahasa Indonesia)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    'id': {
      'app_name': 'Amal',
      'settings': 'Pengaturan',
      'general': 'Umum',
      'language': 'Bahasa',
      'theme': 'Tema Aplikasi',
      'dark_mode': 'Mode Gelap',
      'light_mode': 'Mode Terang',
      'font_size': 'Ukuran Font',
      'notifications': 'Notifikasi',
      'adhan_voice': 'Suara Adzan',
      'pre_prayer_reminder': 'Pengingat Sebelum Shalat (10 mnt)',
      'juma_reminder': 'Pengingat Shalawat Jumat',
      'test_adhan': 'Uji Adzan (dalam 3 dtk)',
      'test_adhan_msg': 'Tutup aplikasi, Adzan akan segera berkumandang',
      'about': 'Tentang',
      'version': 'Versi',
      'team': 'Tim Kami',
      'assalom': 'Assalamu\'alaikum',
      'next_prayer': 'Waktu shalat berikutnya',
      'audio_quran': 'Audio Al-Qur\'an',
      'quran_menu': 'Al-Qur\'an Mulia',
      'mushaf': 'Mushaf (Tajwid)',
      'duas': 'Doa & Shalawat',
      'tasbeh': 'Tasbih',
      'qibla': 'Kiblat',
      'bomdod': 'Subuh',
      'peshin': 'Dzuhur',
      'asr': 'Ashar',
      'shom': 'Maghrib',
      'xufton': 'Isya',
      'uzbek_latin': 'Uzbek (Latin)',
      'uzbek_cyrillic': 'Uzbek (Sirilik)',
      'search_surah': 'Cari Surah...',
      'quran_karim': 'Al-Qur\'an',
      'sura': 'Surah',
      'juz': 'Juz',
      'oyat': 'AYAT',
      'copy_success': 'Ayat disalin',
      'share_msg': '— dari aplikasi Amal',
      'history_stats': 'Riwayat & Statistik',
      'zikr_counter': 'Penghitung Dzikir',
      'select_language': 'Pilih Bahasa',
      'hours': 'jam',
      'minutes': 'menit',
      'seconds': 'detik',
      'listen': 'Dengarkan',
      'menu_subtitle_dua': 'via Menu Masuk',
      'zikr_subtitle': 'Penghitung Dzikir',
      'qibla_subtitle': 'Arah',
      'meccan': 'MAKKIYAH',
      'medinan': 'MADANIYAH',
      'subhanalloh': 'Subhanallah',
      'alhamdulillah': 'Alhamdulillah',
      'allohu akbar': 'Allahu Akbar',
      'la ilaha illalloh': 'La ilaha illallah',
      'astaghfirulloh': 'Astaghfirullah',
      'total_count': 'Total: ',
      'custom_zikr_hint': 'Tulis dzikir kustom...',
      'tonggi duolar': 'Doa Pagi',
      'kechki duolar': 'Doa Sore',
      'namoz duolari': 'Doa Shalat',
      'kundalik duolar': 'Doa Sehari-hari',
      'safar duolari': 'Doa Safar',
      'oila duolari': 'Doa Keluarga',
      'juma duolari': 'Doa Jumat',
      'ramazon duolari': 'Doa Ramadhan',
      'haj va umra': 'Haji & Umrah',
      'bemorlik': 'Orang Sakit',
      'qabr ziyorati': 'Ziarah Kubur',
      'salovatlar': 'Shalawat',
      'duolar': 'Doa',
      'error_occured': 'Terjadi kesalahan',
      'namoz_times': 'Waktu Shalat',
      'current_location': 'Lokasi Saat Ini',
      'change': 'Ubah',
      'select_city': 'Pilih Kota',
      'search_city_hint': 'Ketik nama kota...',
      'my_location_gps': 'Lokasi Saya (GPS)',
      'auto_detection': 'Deteksi Otomatis',
      'calc_settings': 'Pengaturan Perhitungan',
      'calc_method': 'Metode Perhitungan',
      'madhab_title': 'Mazhab (untuk waktu Ashar)',
      'hanafi': 'Hanafi',
      'shafi': 'Syafi\'i / Lainnya',
      'gps_enabled': 'Lokasi GPS diaktifkan',
      'quyosh': 'Terbit',
      'qibla_aligned': 'Kiblat telah lurus!',
      'qibla_hint': 'Pegang ponsel Anda dengan datar dan putar perlahan',
      'auto_detect_method': 'Deteksi Otomatis',
      'auto_detect_hint': 'Otomatis memilih metode perhitungan yang sesuai',
      'calc_method_hint': 'Standar perhitungan berbeda di tiap wilayah. Pilih yang sesuai.',
      'location_denied': 'Akses lokasi ditolak',
      'location_needed': 'Akses lokasi diperlukan',
      'retry': 'Coba lagi',
      'today': 'Hari Ini',
      'streak': 'Beruntun',
      'all': 'Semua',
      'last_7_days': '7 hari terakhir',
      'mon': 'Sen',
      'tue': 'Sel',
      'wed': 'Rab',
      'thu': 'Kam',
      'fri': 'Jum',
      'sat': 'Sab',
      'sun': 'Min',
      'monthly_schedule': 'Jadwal Bulanan',
      'prayer_completed': 'sudah shalat',
      'future_times': 'Waktu akan datang',
      'past_day': 'Hari lalu',
      'full_schedule': 'Jadwal Lengkap',
      'completed_today': 'Hari ini:',
      'of_5_prayers': '/ 5 shalat diselesaikan',
      'daily_prayers': 'Shalat Harian',
      'all_prayers_done': 'Semua shalat diselesaikan. Semoga Allah menerima.',
      'language_sub_en': 'English',
      'language_sub_ar': 'العربية',
      'language_sub_id': 'Bahasa Indonesia',
      'language_sub_uz': 'O\'zbekcha',
    },
  };

  String translate(String key) {
    if (key.isEmpty) return key;
    final k = key.toLowerCase();
    
    // Direct translation from the current language
    final localized = _localizedValues[language]?[k] ?? _localizedValues[language]?[key];
    if (localized != null) return localized;

    // If language is Cyrillic and no direct translation, auto-transliterate from Uzbek Latin
    if (language == 'uz_cyr') {
      final uzValue = _localizedValues['uz']?[k] ?? _localizedValues['uz']?[key];
      if (uzValue != null) return toCyrillic(uzValue);
      return toCyrillic(key);
    }

    // Fallback to English, then Uzbek, then key itself
    final enValue = _localizedValues['en']?[k] ?? _localizedValues['en']?[key];
    if (enValue != null) return enValue;

    final uzValue = _localizedValues['uz']?[k] ?? _localizedValues['uz']?[key];
    if (uzValue != null) return uzValue;

    return key;
  }

  static String toCyrillic(String text) {
    if (text.isEmpty) return text;
    
    Map<String, String> mapping = {
      'sh': 'ш', 'Sh': 'Ш', 'SH': 'Ш',
      'ch': 'ч', 'Ch': 'Ч', 'CH': 'Ч',
      'yo': 'ё', 'Yo': 'Ё', 'YO': 'Ё',
      'yu': 'ю', 'Yu': 'Ю', 'YU': 'Ю',
      'ya': 'я', 'Ya': 'Я', 'YA': 'Я',
      'ye': 'е', 'Ye': 'Е', 'YE': 'Е',
      'o\'': 'ў', 'O\'': 'Ў',
      'g\'': 'ғ', 'G\'': 'Ғ',
      'a': 'а', 'A': 'А',
      'b': 'б', 'B': 'Б',
      'd': 'д', 'D': 'Д',
      'e': 'е', 'E': 'Е',
      'f': 'ф', 'F': 'Ф',
      'g': 'г', 'G': 'Г',
      'h': 'ҳ', 'H': 'Ҳ',
      'i': 'и', 'I': 'И',
      'j': 'ж', 'J': 'Ж',
      'k': 'к', 'K': 'К',
      'l': 'л', 'L': 'Л',
      'm': 'м', 'M': 'М',
      'n': 'н', 'N': 'Н',
      'o': 'о', 'O': 'О',
      'p': 'п', 'P': 'П',
      'q': 'қ', 'Q': 'Қ',
      'r': 'р', 'R': 'Р',
      's': 'с', 'S': 'С',
      't': 'т', 'T': 'Т',
      'u': 'у', 'U': 'У',
      'v': 'в', 'V': 'В',
      'x': 'х', 'X': 'Х',
      'y': 'й', 'Y': 'Й',
      'z': 'з', 'Z': 'З',
      '\'': 'ъ',
    };

    String result = text;
    // Multi-char mappings first
    mapping.forEach((key, value) {
      if (key.length > 1) {
        result = result.replaceAll(key, value);
      }
    });
    // Single-char mappings
    mapping.forEach((key, value) {
      if (key.length == 1) {
        result = result.replaceAll(key, value);
      }
    });

    return result;
  }
}

final localizationProvider = Provider<AppLocalization>((ref) {
  final settings = ref.watch(settingsProvider);
  return AppLocalization(settings.language);
});

extension LocalizationExtension on BuildContext {
  String l10n(String key) {
    return key; 
  }
}
